[2024-03-24 13:00:06] local.INFO: $value [
    {"messaging_product":"whatsapp","metadata":{"display_phone_number":"8801322827722","phone_number_id":"106689602303326"},
    "statuses":[{"id":"wamid.HBgNODgwMTcxMTEwMzY2MhUCABEYEjY2NjY1MEQ5NjM3QUU4ODBFMgA=","status":"failed",
        "timestamp":"1711263605","recipient_id":"8801711103662","errors":[
            {"code":"131042","title":"Message failed to send because there were one or more errors related to your payment method.","href":"
                https://developers.facebook.com/docs/whatsapp/cloud-api/support/error-codes/"}]}]}] 


                [2024-03-24 14:11:51] local.INFO: $value [{"messaging_product":"whatsapp","metadata":{"display_phone_number":"8801322827722","phone_number_id":"106689602303326"},"statuses":[{"id":"wamid.HBgNODgwMTcxMTEwMzY2MhUCABEYEjY4REUzNThFQ0NGQjkzMkI4RgA=","status":"failed","timestamp":"1711267910","recipient_id":"8801711103662","errors":[{"code":"131042","title":"Message failed to send because there were one or more errors related to your payment method.","href":"https://developers.facebook.com/docs/whatsapp/cloud-api/support/error-codes/"}]}]}] 
[2024-03-24 14:11:51] local.INFO: errors [[{"code":"131042","title":"Message failed to send because there were one or more errors related to your payment method.","href":"https://developers.facebook.com/docs/whatsapp/cloud-api/support/error-codes/"}]] 
[2024-03-24 14:11:51] local.INFO: errors ["Message failed to send because there were one or more errors related to your payment method."] 
[2024-03-24 14:11:51] local.INFO: Message Update [{"App\\Models\\Message":{"id":2240,"message_id":"wamid.HBgNODgwMTcxMTEwMzY2MhUCABEYEjY4REUzNThFQ0NGQjkzMkI4RgA=","contact_id":1565,"client_id":1,"conversation_id":null,"template_id":18,"group_subscriber_id":null,"contacts":"","header_text":null,"footer_text":"Pesan ini berasal dari bisnis yang tidak terverifikasi.","header_image":null,"header_audio":null,"header_video":null,"header_location":null,"header_document":null,"buttons":"[{\"type\":\"QUICK_REPLY\",\"text\":\"Ya\"},{\"type\":\"QUICK_REPLY\",\"text\":\"Tidak\"}]","value":"Halo Arifur, apakah kami bisa mengatasi masalah yang sedang Anda hadapi?","component_header":"[]","component_body":"[{\"type\":\"text\",\"text\":\"Arifur\"}]","component_buttons":"[]","error":"Message failed to send because there were one or more errors related to your payment method.","message_type":"text","status":"failed","source":"whatsapp","schedule_at":"2024-03-24 14:11:12","components":"[{\"type\":\"text\",\"text\":\"Arifur\"}]","campaign_id":null,"is_contact_msg":0,"is_campaign_msg":1,"created_by":null,"updated_by":null,"created_at":"2024-03-24T08:11:12.000000Z","updated_at":"2024-03-24T08:11:51.000000Z","deleted_at":null}}] 
[2024-03-24 14:11:51] local.INFO: $incomming_status ["failed"] 
[2024-03-24 14:11:51] local.INFO: $message_id ["wamid.HBgNODgwMTcxMTEwMzY2MhUCABEYEjY4REUzNThFQ0NGQjkzMkI4RgA="] 
[2024-03-24 14:11:51] local.INFO: $message [{"App\\Models\\Message":{"id":2240,"message_id":"wamid.HBgNODgwMTcxMTEwMzY2MhUCABEYEjY4REUzNThFQ0NGQjkzMkI4RgA=","contact_id":1565,"client_id":1,"conversation_id":null,"template_id":18,"group_subscriber_id":null,"contacts":"","header_text":null,"footer_text":"Pesan ini berasal dari bisnis yang tidak terverifikasi.","header_image":null,"header_audio":null,"header_video":null,"header_location":null,"header_document":null,"buttons":"[{\"type\":\"QUICK_REPLY\",\"text\":\"Ya\"},{\"type\":\"QUICK_REPLY\",\"text\":\"Tidak\"}]","value":"Halo Arifur, apakah kami bisa mengatasi masalah yang sedang Anda hadapi?","component_header":"[]","component_body":"[{\"type\":\"text\",\"text\":\"Arifur\"}]","component_buttons":"[]","error":"Message failed to send because there were one or more errors related to your payment method.","message_type":"text","status":"failed","source":"whatsapp","schedule_at":"2024-03-24 14:11:12","components":"[{\"type\":\"text\",\"text\":\"Arifur\"}]","campaign_id":null,"is_contact_msg":0,"is_campaign_msg":1,"created_by":null,"updated_by":null,"created_at":"2024-03-24T08:11:12.000000Z","updated_at":"2024-03-24T08:11:51.000000Z","deleted_at":null}}] 
